name: chow_down
description: A practical Flutter application.

# The following line prevents the package from being accidentally published to
# pub.dev using `pub publish`. This is preferred for private packages.
publish_to: "none" # Remove this line if you wish to publish to pub.dev

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 1.0.0+1

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  # App dependencies
  auto_size_text: ^3.0.0
  another_flushbar: ^1.12.30
  ansi_styles: ^0.3.2+1
  bloc: ^8.0.2
  cached_network_image: ^3.3.0
  cloud_firestore: ^5.0.2
  cupertino_icons: ^1.0.2
  dio: ^5.3.3
  equatable: ^2.0.3
  firebase_auth: ^5.1.1
  firebase_analytics: ^11.1.0
  firebase_core: ^3.1.1
  firebase_crashlytics: ^4.0.2
  flutter_bloc: ^8.0.1
  flutter_dotenv: ^5.0.2
  flutter_phoenix: ^1.1.1
  flutter_spinkit: ^5.1.0
  google_fonts: ^6.1.0
  google_sign_in: ^6.1.5
  json_annotation: ^4.8.1
  json_serializable: ^6.3.1
  path_provider: ^2.0.11
  provider: ^6.0.0
  rxdart: ^0.27.7
  url_launcher: ^6.1.5

dev_dependencies:
  flutter_test:
    sdk: flutter
  build_runner: ^2.4.0
  flutter_launcher_icons: ^0.13.1
  freezed: ^2.4.5
  freezed_annotation: ^2.4.1
  flutter_native_splash: ^2.0.0
  import_sorter: ^4.6.0

flutter_native_splash:
  color: "#000000"
  image: assets/images/logo.png

flutter_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/images/logo.png"
# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:
  uses-material-design: true

  assets:
    - .env
    - assets/images/

  fonts:
    - family: Lato
      fonts:
        - asset: fonts/Lato-Regular.ttf
        - asset: fonts/Lato-Bold.ttf
          # style: italic
    # - family: RobotoMono
    #   fonts:
    #     - asset: fonts/RobotoMono-Regular.ttf
    #     - asset: fonts/RobotoMono-Bold.ttf
    #       weight: 700

# run in pre-commit
import_sorter:
  emojis: true
  comments: true
  ignored_files: []
# sorter remove ignore implementation_imports
